### PR TITLE
Options support

### PR DESCRIPTION
**Pull request by bossanova808**
Ok here it is.  Pretty simple in the end, and it keeps the syntax consistent with regular addToCart and the MultiAdd approach.

Added to the docs too (code pinched from the Commerce examples).

I will not lie, testing has been....light.  _It works for me_ (tm).  But I am using only one option, haven't got anything that uses multiples.  I am sure if someone does and it breaks, they'll let us know ;)

### CODE REVIEW

**Comment by bossanova808** [comment]
Apologies for the 3 commits, too - but github went arse up during this, so I got a bit confused.  I guess I could squash but I doubt we care that much right?

**Comment by bossanova808** [comment]
Hey Josh - you get to looking at this yet? I presume you're going to go the other, simpler way?

It's quite possible this is even more standard way of doing it, I've got no idea really (i.e. `<input type="text" name="items[0][options][size]" placeholder="Size.."/>` - I just came at it from the angle of keeping it the same as the non multi-add syntax.

I can PR up the other version if you like, would be good to get this in a others are bound to use it...

**Comment by engram-design** [comment]
Hey Jeremy, sorry for my slackness - I've not had a chance to test this yet. Are you leaning towards a simpler version? I'm happy with whatever the standard approach is, and one that is closest to how Commerce works (one can dream we will someday not rely on this plugin at all).

I much prefer the non-nested approach as its easier to read and makes the most sense. I've never really used nested stuff, but my understanding is its the same end result?

Anyway, let me know and happy to look into this quickly.

**Comment by bossanova808** [comment]
Yep, I think non nested is obviously nicer here, and the code is simpler too, so I've changed that, updated docs and bumped the version number too.  Was going to create a little multi cart logo but then realised I have a billion other more important things to do :)

Working fine here.

**Comment by engram-design** [comment]
Haha, don't we all! :smiley: Thanks for organising this - really appreciated!

**Pull request merged**
