### PR TITLE
New fast controller

### PR DESCRIPTION
**Pull request by bossanova808**
As you saw in Slack I made a faster controller to deal better with adding lots of items at once and as a bonus it means you get proper rollback on error.

Also added a basic changelog.

I have kept the old, tested controller as this is new and that way nothing existing should break, but I think this approach is a lot better and once a bit more used/tested should be the default (in lieu of a proper controller from P & T obviously!).

Your thoughs appreciated when you have a minute.

### CODE REVIEW

**Comment by jameslindeman** [comment]
Repeat from Slack: In addition, how about a conditional at the beginning of that foreach in the service, so items with qty=0 don’t run those extra lineItem checks? Some like: 

```
foreach ($items as $key => $item) {

    $qty = isset($item['qty']) ? (int)$item['qty'] : 0;

    if ($qty != 0) {

        $purchasableId    = $item['purchasableId'];
```

**Comment by bossanova808** [comment]
Yep will do.  And after talking with Josh idea is to simply sub this in for the normal multiadd controller as it's better across the board, so I'll do that in the next few hours and then we'll merge it in.

Thanks for checking it!

**Comment by engram-design** [comment]
@jameslindeman I'm all for that - good thinking!

**Comment by bossanova808** [comment]
Ok Josh should be good to go - removed the old controller and added the qty check.  Also, using phpstorm now so there's phpdoc in there for whatever that's worth!

**Comment by engram-design** [comment]
Nice work chaps!

**Pull request merged**
